package bridge

import (
	"bytes"
	"errors"
	"strings"
	"testing"
)

const completeTemporaryCredentials = `[default]
aws_access_key_id = access-value
aws_secret_access_key = secret-value
aws_session_token = token-value
`

func TestFilterHostDefaultSnapshotAcceptsLeappStyleTemporaryDefault(t *testing.T) {
	snapshot := HostAWSDirectorySnapshot{
		Config:      []byte("[default]\noutput = json\nregion = us-west-2\n[profile engineering]\nregion=eu-west-1\n"),
		Credentials: []byte(completeTemporaryCredentials + "[engineering]\naws_access_key_id=named-access\naws_secret_access_key=named-secret\n"),
	}
	filtered, state, err := FilterHostDefaultSnapshot(snapshot)
	if err != nil || state != HostDefaultAvailable {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	if got, want := string(filtered.Config), "[default]\noutput=json\nregion=us-west-2\n"; got != want {
		t.Fatalf("config = %q, want %q", got, want)
	}
	if got, want := string(filtered.Credentials), "[default]\naws_access_key_id=access-value\naws_secret_access_key=secret-value\naws_session_token=token-value\n"; got != want {
		t.Fatalf("credentials = %q, want %q", got, want)
	}
	if bytes.Contains(filtered.Config, []byte("engineering")) || bytes.Contains(filtered.Credentials, []byte("named-")) {
		t.Fatal("named profile reached filtered snapshot")
	}
}

func TestFilterHostDefaultSnapshotAllowsOptionalConfig(t *testing.T) {
	filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{Credentials: []byte(completeTemporaryCredentials)})
	if err != nil || state != HostDefaultAvailable {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	if filtered.Config != nil {
		t.Fatalf("absent config encoded as %q", filtered.Config)
	}
	if len(filtered.Credentials) == 0 {
		t.Fatal("complete credentials were omitted")
	}
}

func TestFilterHostDefaultSnapshotValidatesButOmitsNamedSections(t *testing.T) {
	snapshot := HostAWSDirectorySnapshot{
		Config:      []byte("[profile named]\ncredential_process = should-be-ignored\n[default]\nregion=us-east-1\n"),
		Credentials: []byte("[named]\ncredential_process=should-be-ignored\n" + completeTemporaryCredentials),
	}
	filtered, state, err := FilterHostDefaultSnapshot(snapshot)
	if err != nil || state != HostDefaultAvailable {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	if bytes.Contains(filtered.Config, []byte("process")) || bytes.Contains(filtered.Credentials, []byte("process")) {
		t.Fatal("named authority reference reached filtered snapshot")
	}
}

func TestFilterHostDefaultSnapshotPreservesEqualsInValues(t *testing.T) {
	filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
		Config:      []byte("[default]\noutput=prefix=value\n"),
		Credentials: []byte("[default]\naws_access_key_id=AKIA=part\naws_secret_access_key=secret==\naws_session_token=a=b=c\n"),
	})
	if err != nil || state != HostDefaultAvailable {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	for _, expected := range [][]byte{[]byte("output=prefix=value\n"), []byte("aws_access_key_id=AKIA=part\n"), []byte("aws_secret_access_key=secret==\n"), []byte("aws_session_token=a=b=c\n")} {
		if !bytes.Contains(append(filtered.Config, filtered.Credentials...), expected) {
			t.Fatalf("filtered output omitted %q", expected)
		}
	}
}

func TestFilterHostDefaultSnapshotNormalizesCommentsWhitespaceAndLineEndings(t *testing.T) {
	filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
		Config:      []byte(" ; comment\r\n[default] \r\nregion = us-east-2 \r\n# other comment\r\n"),
		Credentials: []byte(" # generated by Leapp\r\n[default] \r\nAWS_SESSION_TOKEN = token \r\naws_secret_access_key = secret \r\naws_access_key_id = access \r\n"),
	})
	if err != nil || state != HostDefaultAvailable {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	if got := string(filtered.Config); got != "[default]\nregion=us-east-2\n" {
		t.Fatalf("normalized config = %q", got)
	}
	if got := string(filtered.Credentials); got != "[default]\naws_access_key_id=access\naws_secret_access_key=secret\naws_session_token=token\n" {
		t.Fatalf("normalized credentials = %q", got)
	}
}

func TestFilterHostDefaultSnapshotMissingDefaultIsUnavailable(t *testing.T) {
	filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
		Config:      []byte("[default]\nregion=us-east-1\n"),
		Credentials: []byte("[named]\naws_access_key_id=access\naws_secret_access_key=secret\naws_session_token=token\n"),
	})
	if err != nil || state != HostDefaultUnavailable {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	assertEmptyHostDefaultSnapshot(t, filtered)
}

func TestFilterHostDefaultSnapshotClassifiesIncompleteAndLongLivedDefault(t *testing.T) {
	for _, test := range []struct {
		name        string
		credentials string
		want        HostDefaultState
	}{
		{name: "empty section", credentials: "[default]\n", want: HostDefaultUnavailable},
		{name: "long-lived key pair", credentials: "[default]\naws_access_key_id=access\naws_secret_access_key=secret\n", want: HostDefaultUnsupported},
		{name: "missing access key", credentials: "[default]\naws_secret_access_key=secret\naws_session_token=token\n", want: HostDefaultUnavailable},
		{name: "missing secret key", credentials: "[default]\naws_access_key_id=access\naws_session_token=token\n", want: HostDefaultUnavailable},
		{name: "empty session token", credentials: "[default]\naws_access_key_id=access\naws_secret_access_key=secret\naws_session_token=   \n", want: HostDefaultUnsupported},
	} {
		t.Run(test.name, func(t *testing.T) {
			filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{Credentials: []byte(test.credentials)})
			if err != nil || state != test.want {
				t.Fatalf("filter state = %q, want %q, error = %v", state, test.want, err)
			}
			assertEmptyHostDefaultSnapshot(t, filtered)
		})
	}
}

func TestFilterHostDefaultSnapshotRejectsEveryForbiddenAuthorityClass(t *testing.T) {
	for _, test := range []struct {
		name string
		key  string
	}{
		{name: "credential material in config", key: "aws_secret_access_key"},
		{name: "process provider", key: "credential_process"},
		{name: "credential source", key: "credential_source"},
		{name: "source profile", key: "source_profile"},
		{name: "web identity file", key: "web_identity_token_file"},
		{name: "role chain", key: "role_arn"},
		{name: "role external id", key: "external_id"},
		{name: "role MFA", key: "mfa_serial"},
		{name: "SSO URL", key: "sso_start_url"},
		{name: "SSO session", key: "sso_session"},
		{name: "service section reference", key: "services"},
		{name: "login session", key: "login_session"},
		{name: "external config file", key: "config_file"},
		{name: "external credentials file", key: "shared_credentials_file"},
		{name: "custom endpoint", key: "endpoint_url"},
		{name: "unknown ARN reference", key: "custom_arn"},
		{name: "unknown process reference", key: "custom_process"},
		{name: "unknown profile reference", key: "custom_profile"},
		{name: "unknown token file reference", key: "custom_token_file"},
	} {
		t.Run(test.name, func(t *testing.T) {
			filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
				Config:      []byte("[default]\n" + test.key + "=reference\n"),
				Credentials: []byte(completeTemporaryCredentials),
			})
			if err != nil || state != HostDefaultUnsupported {
				t.Fatalf("filter state = %q, %v", state, err)
			}
			assertEmptyHostDefaultSnapshot(t, filtered)
		})
	}
}

func TestFilterHostDefaultSnapshotRejectsCredentialFileAuthorityReference(t *testing.T) {
	filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
		Credentials: []byte(completeTemporaryCredentials + "credential_process=external-provider\n"),
	})
	if err != nil || state != HostDefaultUnsupported {
		t.Fatalf("filter state = %q, %v", state, err)
	}
	assertEmptyHostDefaultSnapshot(t, filtered)
}

func TestFilterHostDefaultSnapshotRejectsDuplicateMalformedControlAndContinuationInput(t *testing.T) {
	for _, test := range []struct {
		name  string
		input string
	}{
		{name: "duplicate default section", input: "[default]\nregion=one\n[default]\nregion=two\n"},
		{name: "duplicate named section", input: "[named]\nregion=one\n[named]\nregion=two\n"},
		{name: "duplicate key", input: "[default]\nregion=one\nREGION=two\n"},
		{name: "duplicate named key", input: "[named]\nregion=one\nREGION=two\n"},
		{name: "malformed header", input: "[default\nregion=one\n"},
		{name: "trailing header data", input: "[default] trailing\nregion=one\n"},
		{name: "empty header", input: "[]\nregion=one\n"},
		{name: "entry before section", input: "region=one\n"},
		{name: "malformed entry", input: "[default]\nregion one\n"},
		{name: "continuation", input: "[default]\nregion=one\n  continued-value\n"},
		{name: "nested continuation entry", input: "[default]\ns3=\n  max_concurrent_requests=10\n"},
		{name: "NUL control", input: "[default]\nregion=one\x00two\n"},
		{name: "tab control", input: "[default]\nregion=one\ttwo\n"},
		{name: "bare carriage return", input: "[default]\rregion=one\n"},
		{name: "invalid UTF-8", input: "[default]\nregion=\xff\n"},
	} {
		t.Run(test.name, func(t *testing.T) {
			filtered, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{Config: []byte(test.input), Credentials: []byte(completeTemporaryCredentials)})
			if !errors.Is(err, ErrHostDefaultMalformed) || state != HostDefaultUnavailable {
				t.Fatalf("filter state = %q, error = %v", state, err)
			}
			assertEmptyHostDefaultSnapshot(t, filtered)
		})
	}
}

func TestFilterHostDefaultSnapshotEnforcesSizeAndStructuralLimits(t *testing.T) {
	t.Run("source bytes", func(t *testing.T) {
		input := bytes.Repeat([]byte{'x'}, maxHostDefaultSourceBytes+1)
		_, _, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{Config: input, Credentials: []byte(completeTemporaryCredentials)})
		if !errors.Is(err, ErrHostDefaultOversized) {
			t.Fatalf("error = %v", err)
		}
	})

	for _, test := range []struct {
		name  string
		input func() []byte
	}{
		{name: "section count", input: func() []byte {
			var input strings.Builder
			for index := 0; index <= maxHostDefaultSections; index++ {
				input.WriteString("[section-")
				input.WriteString(strings.Repeat("x", index/maxHostDefaultSections))
				input.WriteByte(byte('A' + index%26))
				input.WriteString(strings.Repeat("z", index/26))
				input.WriteString("]\n")
			}
			return []byte(input.String())
		}},
		{name: "key count", input: func() []byte {
			var input strings.Builder
			input.WriteString("[default]\n")
			for index := 0; index <= maxHostDefaultKeys; index++ {
				input.WriteString("key")
				input.WriteString(base26HostDefaultTestName(index))
				input.WriteString("=value\n")
			}
			return []byte(input.String())
		}},
		{name: "section name bytes", input: func() []byte {
			return []byte("[" + strings.Repeat("a", maxHostDefaultNameBytes+1) + "]\n")
		}},
		{name: "key name bytes", input: func() []byte {
			return []byte("[default]\n" + strings.Repeat("a", maxHostDefaultKeyBytes+1) + "=value\n")
		}},
		{name: "line bytes", input: func() []byte {
			return []byte("[default]\nregion=" + strings.Repeat("a", maxHostDefaultLineBytes) + "\n")
		}},
	} {
		t.Run(test.name, func(t *testing.T) {
			_, state, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{Config: test.input(), Credentials: []byte(completeTemporaryCredentials)})
			if !errors.Is(err, ErrHostDefaultLimitExceeded) || state != HostDefaultUnavailable {
				t.Fatalf("filter state = %q, error = %v", state, err)
			}
		})
	}
}

func TestFilterHostDefaultSnapshotIsDeterministic(t *testing.T) {
	left, leftState, leftErr := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
		Config:      []byte("[default]\nregion = us-west-1\noutput=json\n"),
		Credentials: []byte("[default]\naws_session_token=token\naws_access_key_id=access\naws_secret_access_key=secret\n"),
	})
	right, rightState, rightErr := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{
		Config:      []byte("; generated\r\n[default]\r\noutput = json\r\nregion=us-west-1\r\n"),
		Credentials: []byte("[default]\r\nAWS_SECRET_ACCESS_KEY = secret\r\nAWS_ACCESS_KEY_ID=access\r\nAWS_SESSION_TOKEN = token\r\n"),
	})
	if leftErr != nil || rightErr != nil || leftState != HostDefaultAvailable || rightState != HostDefaultAvailable {
		t.Fatalf("states = %q/%q, errors = %v/%v", leftState, rightState, leftErr, rightErr)
	}
	if !bytes.Equal(left.Config, right.Config) || !bytes.Equal(left.Credentials, right.Credentials) {
		t.Fatalf("non-deterministic output: %#v != %#v", left, right)
	}
}

func TestFilterHostDefaultSnapshotErrorsNeverContainSourceBytes(t *testing.T) {
	secret := "never-echo-this-secret-value"
	inputs := [][]byte{
		[]byte("[default]\naws_secret_access_key=" + secret + "\nmalformed continuation\n"),
		append([]byte("[default]\nregion="+secret), 0),
		bytes.Repeat([]byte(secret), maxHostDefaultSourceBytes/len(secret)+1),
	}
	for _, input := range inputs {
		_, _, err := FilterHostDefaultSnapshot(HostAWSDirectorySnapshot{Config: input, Credentials: []byte(completeTemporaryCredentials)})
		if err == nil {
			t.Fatal("invalid secret-bearing source was accepted")
		}
		if strings.Contains(err.Error(), secret) {
			t.Fatalf("error exposed source bytes: %q", err)
		}
	}
}

func assertEmptyHostDefaultSnapshot(t *testing.T, snapshot HostAWSDirectorySnapshot) {
	t.Helper()
	if len(snapshot.Config) != 0 || len(snapshot.Credentials) != 0 {
		t.Fatalf("non-available result retained bytes: config=%d credentials=%d", len(snapshot.Config), len(snapshot.Credentials))
	}
}

func base26HostDefaultTestName(value int) string {
	var encoded [8]byte
	position := len(encoded)
	for {
		position--
		encoded[position] = byte('a' + value%26)
		value /= 26
		if value == 0 {
			return string(encoded[position:])
		}
	}
}
